encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.entry, name="entry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("wiki/", include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request, entry):
    return render(
        request,
        "encyclopedia/entry.html",
        {"entry": util.get_entry(entry)},
    )

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
<!--  -->
{% load markdownify %}
<!--  -->
{% block title %}
<!--  -->
Encyclopedia
<!--  -->
{% endblock %}
<!--  -->
{% block body %}
<p>{{ entry | markdownify}}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
<!--  -->
{% block title %}
<!--  -->
Encyclopedia
<!--  -->
{% endblock %}
<!--  -->
{% block body %}
<h1>All Pages</h1>
<ul>
  {% for entry in entries %}
  <li><a href="{% url 'wiki:entry' entry%}">{{ entry }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div class="row">
      <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form>
          <input
            class="search"
            type="text"
            name="q"
            placeholder="Search Encyclopedia"
          />
        </form>
        <div>
          <a href="{% url 'wiki:index' %}">Home</a>
        </div>
        <div>Create New Page</div>
        <div>Random Page</div>
        {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9">{% block body %} {% endblock %}</div>
    </div>
  </body>
</html>